spring:
  profiles.active: default
---
spring:
  datasource:
    url:
    driver-class-name:
  http:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
  elastic:
    elasticsearch.clustername : elasticsearch
    elasticsearch.host : 18.220.91.47
    elasticsearch.port : 9200
logging:
  level.com.trpo.lectureRepo: DEBUG
  file: ./lectureRepo.log
data-update-schedule:
  indexing: 0 0/5 * * * MON-FRI # every Friday at 12:00